name: task-b manual

on: 
  workflow_dispatch:
    inputs:
      message:
        description: 'Message'
        required: true
        default: 'Hello CI/CD'
      
      tag:
        description: 'Tag'
        required: True
        default: 'default-tag'

      # TODO: add tag input

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: "ubuntu-latest"
    name: Docker build
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Replace message in index.hml
        run: sed -i "s#DEFAULT_MESSAGE#${{ inputs.message }}#" ./task_b/index.html
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN  }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=ref,event=tag

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: task_b
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ inputs.tag }}
      # TODO: build and push docker image
      
  test:
    needs: docker
    runs-on: "ubuntu-latest"
    name: Test

    services:
      test-service:
        image: ghcr.io/${{ github.repository }}:${{ inputs.tag }} 
        ports:
          - 8080:80
    
    steps:
      - name: Fetch index
        run: curl 127.0.0.1:8080/index.html
    
      # TODO: Add test job
